[package]
name = "vegalite"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["j-mueller"]
license = "MIT"
description = "Generate charts with vegalite."

repository = "https://github.com/j-mueller/typst-vegalite"

keywords = ["charts", "plot", "vegalite"]

exclude = ["examples"]